name: danmaku-go
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Compile
        run: go build -o danmaku-go

      - name: Save key to file
        run: echo ${{ secrets.ALIYUN_SERVER_KEY }} > id_rsa
        shell: bash

      - name: Upload
        run: scp -i id_rsa danmaku-go root@www.icestream32.cn:/root/action

    #   - name: Connect aliyun server
    #     run: echo ${{ secrets.ALIYUN_SERVER_KEY }} | ssh -o "IdentityFile=/dev/stdin" root@www.icestream32.cn
